# Generated by Django 5.0.1 on 2024-02-01 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('PublishedDate', models.DateField()),
                ('Genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('DetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfPages', models.IntegerField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=50)),
                ('Book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'db_table': 'BookDetails',
            },
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField()),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'BorrowedBooks',
            },
        ),
    ]
