# Generated by Django 5.0.1 on 2024-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('MembershipDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserAccounts',
            },
        ),
    ]
